branches:
  only:
    - master
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - haveged
rvm:
  - 2.3.0
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-9.1.5.0
