# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-hl7 1.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-hl7".freeze
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Mark Guzman".freeze]
  s.date = "2021-04-23"
  s.description = "A simple library to parse and generate HL7 2.x messages".freeze
  s.email = "ruby-hl7@googlegroups.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "NOTES.md",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "examples/proxy_server.rb",
    "lib/core_ext/date_time.rb",
    "lib/core_ext/string.rb",
    "lib/message.rb",
    "lib/message_parser.rb",
    "lib/ruby-hl7.rb",
    "lib/segment.rb",
    "lib/segment_default.rb",
    "lib/segment_fields.rb",
    "lib/segment_generator.rb",
    "lib/segment_list_storage.rb",
    "lib/segments/aig.rb",
    "lib/segments/ail.rb",
    "lib/segments/aip.rb",
    "lib/segments/ais.rb",
    "lib/segments/dg1.rb",
    "lib/segments/err.rb",
    "lib/segments/evn.rb",
    "lib/segments/ft1.rb",
    "lib/segments/fts.rb",
    "lib/segments/gt1.rb",
    "lib/segments/in1.rb",
    "lib/segments/mfe.rb",
    "lib/segments/mfi.rb",
    "lib/segments/mrg.rb",
    "lib/segments/msa.rb",
    "lib/segments/msh.rb",
    "lib/segments/nk1.rb",
    "lib/segments/nte.rb",
    "lib/segments/obr.rb",
    "lib/segments/obx.rb",
    "lib/segments/orc.rb",
    "lib/segments/oru.rb",
    "lib/segments/pid.rb",
    "lib/segments/prd.rb",
    "lib/segments/pv1.rb",
    "lib/segments/pv2.rb",
    "lib/segments/qrd.rb",
    "lib/segments/qrf.rb",
    "lib/segments/rf1.rb",
    "lib/segments/rgs.rb",
    "lib/segments/sch.rb",
    "lib/segments/sft.rb",
    "lib/segments/spm.rb",
    "lib/segments/tq1.rb",
    "lib/segments/txa.rb",
    "lib/test/hl7_messages.rb",
    "ruby-hl7.gemspec",
    "spec/ail_segment_spec.rb",
    "spec/aip_segment_spec.rb",
    "spec/basic_parsing_spec.rb",
    "spec/batch_parsing_spec.rb",
    "spec/child_segment_spec.rb",
    "spec/core_ext/date_time_spec.rb",
    "spec/default_segment_spec.rb",
    "spec/dg1_spec.rb",
    "spec/dynamic_segment_def_spec.rb",
    "spec/err_segment_spec.rb",
    "spec/evn_segment_spec.rb",
    "spec/ft1_segment_spec.rb",
    "spec/fts_segment_spec.rb",
    "spec/gt1_segment_spec.rb",
    "spec/in1_segment_spec.rb",
    "spec/message_spec.rb",
    "spec/messages_spec.rb",
    "spec/mfe_segment_spec.rb",
    "spec/mfi_segment_spec.rb",
    "spec/msa_segment_spec.rb",
    "spec/msh_segment_spec.rb",
    "spec/nk1_segment_spec.rb",
    "spec/obr_segment_spec.rb",
    "spec/obx_segment_spec.rb",
    "spec/orc_segment_spec.rb",
    "spec/pid_segment_spec.rb",
    "spec/prd_segment_spec.rb",
    "spec/pv1_segment_spec.rb",
    "spec/rf1_segment_spec.rb",
    "spec/sch_segment_spec.rb",
    "spec/segment_field_spec.rb",
    "spec/segment_generator_spec.rb",
    "spec/segment_list_storage_spec.rb",
    "spec/segment_spec.rb",
    "spec/sft_segment_spec.rb",
    "spec/spec_helper.rb",
    "spec/speed_parsing_spec.rb",
    "spec/spm_segment_spec.rb",
    "test_data/adt_a01.hl7",
    "test_data/cerner/cerner_bordetella.hl7",
    "test_data/cerner/cerner_en.hl7",
    "test_data/cerner/cerner_lead.hl7",
    "test_data/cerner/cerner_sequential.hl7",
    "test_data/empty-batch.hl7",
    "test_data/empty.hl7",
    "test_data/empty_segments.hl7",
    "test_data/lotsunknowns.hl7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase1.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase2.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase3.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase4.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase5.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase6.er7",
    "test_data/obxobr.hl7",
    "test_data/realm/realm-animal-rabies.hl7",
    "test_data/realm/realm-bad-batch.hl7",
    "test_data/realm/realm-batch.hl7",
    "test_data/realm/realm-campylobacter-jejuni.hl7",
    "test_data/realm/realm-cj-badloinc.hl7",
    "test_data/realm/realm-cj-joeslab.hl7",
    "test_data/realm/realm-cj.hl7",
    "test_data/realm/realm-err.hl7",
    "test_data/realm/realm-hepatitis-c-virus.hl7",
    "test_data/realm/realm-lead-laboratory-result.hl7",
    "test_data/realm/realm-minimal-message.hl7",
    "test_data/rqi_r04.hl7",
    "test_data/test.hl7",
    "test_data/test2.hl7"
  ]
  s.homepage = "http://github.com/toppa/ruby-hl7".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.6".freeze
  s.summary = "Ruby HL7 Library".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<bundler>.freeze, ["~> 2.2"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    s.add_development_dependency(%q<rake>.freeze, [">= 12.3.3"])
    s.add_development_dependency(%q<rake-contrib>.freeze, [">= 0"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.3"])
    s.add_development_dependency(%q<rspec>.freeze, [">= 3.9.0"])
    s.add_development_dependency(%q<simplecov>.freeze, ["= 0.16.1"])
    s.add_development_dependency(%q<simplecov-html>.freeze, ["~> 0.10.0"])
  else
    s.add_dependency(%q<bundler>.freeze, ["~> 2.2"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, [">= 12.3.3"])
    s.add_dependency(%q<rake-contrib>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 6.3"])
    s.add_dependency(%q<rspec>.freeze, [">= 3.9.0"])
    s.add_dependency(%q<simplecov>.freeze, ["= 0.16.1"])
    s.add_dependency(%q<simplecov-html>.freeze, ["~> 0.10.0"])
  end
end

